// flow-typed signature: 0970b19e7f772c7313737763f1c6a993
// flow-typed version: <<STUB>>/postcss-color-hex-alpha_v^3.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-color-hex-alpha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-color-hex-alpha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-color-hex-alpha/index' {
  declare module.exports: $Exports<'postcss-color-hex-alpha'>;
}
declare module 'postcss-color-hex-alpha/index.js' {
  declare module.exports: $Exports<'postcss-color-hex-alpha'>;
}
