// flow-typed signature: 62ca971a05fca4f7bae636a729e875e5
// flow-typed version: <<STUB>>/postcss-map_v^0.9.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-map/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-map/dist/visitor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-map/dist/index.js' {
  declare module.exports: $Exports<'postcss-map/dist/index'>;
}
declare module 'postcss-map/dist/visitor.js' {
  declare module.exports: $Exports<'postcss-map/dist/visitor'>;
}
declare module 'postcss-map/index' {
  declare module.exports: $Exports<'postcss-map'>;
}
declare module 'postcss-map/index.js' {
  declare module.exports: $Exports<'postcss-map'>;
}
